name: Build Python Package

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[training,testing,quality]

      - name: Check isort
        uses: isort/isort-action@v1

      - name: Check black
        run: |
          black --check --diff --preview .

      - name: Check pylint
        run: |
          pylint $(git ls-files '*.py')

      - name: Test with pytest
        run: |
          pytest
